package com.kingrealms.realms.territory.base.response;

public enum ClaimResponse {
    SUCCESS, ALREADY_CLAIMED, CLAIMED_OTHER, NOT_TOUCHING_EXISTING, NOT_A_MEMBER, NO_PERMISSION, NOT_CLAIMED, UNKOWN_ERROR, IN_SPAWN, IN_WARZONE, CLAIM_LIMIT, CLAIM_ACTOR_HIGHER
}