name: Enforcer
version: ${project.version}
main: com.stardevmc.enforcer.Enforcer
authors: [Firestar311]
api-version: 1.15
description: Punishment system by Firestar311
softdepend: [Vault]
depend: [StarLib]
commands:
    moderatorrules:
        aliases: [mrules]
    enforcer:
        aliases: [enf]
    punish:
        aliases: [pu]
    ban:
    tempban:
        aliases: [tb]
    mute:
    tempmute:
        aliases: [tm]
    kick:
    warn:
    jail:
    unban:
    unmute:
    unjail:
    pardon:
    history:
    staffhistory:
    prison:
        aliases: [p]
    report:
        aliases: [r]
    reportadmin:
        aliases: [ra]
    punishment:
    trainingmode:
    blacklist:
    unblacklist:
    watchlist:
        aliases: [wl]
    quickteleport:
        aliases: [qtp]
    rules:
    wave: