package com.kingrealms.realms.items;

public enum ItemType {
    RESOURCE, MINING_RESOURCE_CORE, MYSTICAL_SLIVER, TOOL, SLAYER_RESOURCE_PART, MINING_RESOURCE_PART, FARMING_RESOURCE_CORE, FARMING_RESOURCE_PART, SLAYER_RESOURCE_CORE, CRAFTING_RESOURCE_CORE, LEGENDARY_WEAPON, WOODCUTTING_RESOURCE_CORE, LEGENDARY_ITEM, WOODCUTTING_RESOURCE_PART
}