name: TitanChat
version: ${project.version}
main: com.stardevmc.chat.TitanChat
authors: [Firestar311]
description: Chat Plugin by Firestar311
api-version: 1.14
depend: [FireLib, Vault]
commands:
    chatroom:
        aliases: [cr, chat, c]