name: ${project.name}
version: ${project.version}
main: net.firecraftmc.hub.CenturionsHub
description: HungerMania's Hub
depend: [CenturionsCore]
commands:
    testadmin:
    fly:
    hologram:
    leaderboard:
    npc: