name: IronHavenSB
author: CraftYun38, AloneMusk
version: 1.0
main: com.craftyun83.ironhavensb.Main
api-version: 1.16
depend: [WorldEdit, Vault]

commands:
  is:
    description: Skyblock main command!