name: FireLib
version: ${version}
main: com.firestar311.lib.FireLib
api-version: 1.14
description: The library plugin for all of Firestar311's Plugins
author: Firestar311
softdepend: [Vault]
commands:
    customitem:
        aliases: [cui]
    superadmins:
    hierarchy:
        aliases: [ha]
    #testsql: