package net.brutuspvp.core.enums;

public enum Toggle {
	ADMINMODE, EDITMODE, FRIEND_REQUEST, VANISH_JOIN_LEAVE, RENEWAL_APARTMENT, RENEWAL_HOUSE, RENEWAL_MANSION, 
	PVP, GOD, FLY, MESSAGES, TELEPORTING;
}