
emerald: "20"
diamond: "10"
gold: "5"
iron: "3"

GUIS:
  BiomeGUI:
    - '&8Jungle Biome;JUNGLE_WOOD;1;&aGenerate a jungle biome skyblock island!'
    - '&8Spruce Biome;SPRUCE_WOOD;3;&aGenerate a spruce biome skyblock island!'
    - '&8Forest Biome;OAK_WOOD;5;&aGenerate a forest biome skyblock island!'
    - '&8Savannah Biome;ACACIA_WOOD;7;&aGenerate a savannah biome skyblock island!'
    - '&8Classic;GRASS_BLOCK;11;&aGenerate a classic skyblock island!'
    - '&8Hardcore;BARRIER;15;&aGenerate a hardcore skyblock island!'
  CreatedGUI:
    - '&8Teleport;END_PORTAL_FRAME;4;&6&lTeleport to your island!'
    - '&8Upgrades;DIAMOND;2;&6&lUpgrade your island!'
    - '&8Delete Island;DIAMOND;8;&6&lDelete your current progress and start over!'
    - '&8Invite Friends;PAPER;6;&6&lInvite friends to be a part of your island!'
  CreateGUI:
    - '&8Create Island;GREEN_CONCRETE;4;&6&lCreate your island now!'
  InviteGUI:
    - '&8Info;WITHER_SKELETON_SKULL;4;&6&l%invitor% has invited you to join their coop!'
    - '&a&lAccept;GREEN_CONCRETE;2;&6&lAccept coop invitation'
    - '&c&lDecline;RED_CONCRETE;6;&6&lDecline coop invitation'
  ReloadGUI:
    - '&c&lCancel;RED_CONCRETE;5;&6&lGo back!'
    - '&a&lConfirm;GREEN_CONCRETE;3;&6&lDelete my island!'