name: ${project.name}
version: ${project.version}
main: net.firecraftmc.maniacore.CenturionsCorePlugin
authors: [Firestar311]
description: Library Plugin for OldHM
website: firecraftmc.net
depend: [TimoCloud,LuckPerms,Vault]
commands:
    incognito:
        aliases: [i]
    message:
        aliases: [whisper, msg, tell]
    me:
    broadcast:
        aliases: [bc]
    memory:
        aliases: [mem, tps]
    say:
    stats:
    toggle:
    reply:
        aliases: [r]
    ignore:
    rank:
    friends:
        aliases: [f]
    setstat:
    perks:
    mutations:
    tester:
    nick:
    unnick:
    realname:
    setspawn:
    spawn:
    user: