package com.stardevmc.titanterritories.core.objects.enums;

public enum Permission {
    
    BUILD, DOOR, CONTAINER, NAME, DESCRIPTION, MOTD, INVITE, KICK, TITLE, SPAWNPOINT, SETSPAWNPOINT, WITHDRAW, DEPOSIT, CLAIM, DISBAND, FLAGS, PERMISSIONS,
    UNCLAIM, CREATE_ANNOUNCEMENT, EDIT_ANNOUCNEMENT, CONTROL_ANNOUNCEMENT, MANAGE_RANKS, RELATION_VIEW, RELATION_MANAGE, CREATE_WARP, REMOVE_WARP, EDIT_WARPS, REMOVE_INVITE, REMOVE_USER, BAN_PLAYERS, REDSTONE
}