package com.stardevmc.chat.api;

public enum RoomPermission {
    MANAGE_DISPLAYNAME, MANAGE_FORMAT, MANAGE_DESCRIPTION, MANAGE_ICON, MANAGE_PARTICIPANTS, INVITE, MANAGE_GLOBAL, BAN, UNBAN, READ_MESSAGES, MANAGE_PERMISSION, SEND_MESSAGES
}