name: TitanSpawners
version: ${project.version}
main: net.stardevmc.titanspawners.TitanSpawners
api-version: 1.13
depend: [FireLib]
authors: [Firestar311]
description: A SilkSpanwers plugin by StarDevMC
commands:
    titanspawners:
        aliases: [tsp, spawner, sp]
